In [35]:
# Packages for Data Analysis
import pandas as pd
import numpy as np
# from sklearn import load_boston
from sklearn import linear_model  # this model can not be used when the relationship between independent and dependent variables are not linear
from sklearn.model_selection import train_test_split # function for splitting data into traning and tests sets

In [10]:
#load the boston housing dataset
from sklearn.datasets import load_boston
boston_housing = load_boston()
# print(boston_housing)

In [12]:
# Dataset is messy, transform into a dataframe
#data = independent variables (x variables)
#features = column names of data or labels
#target = dependant variables or y values or price of houses

df_x = pd.DataFrame(boston_housing.data, columns=boston_housing.feature_names)
df_y = pd.DataFrame(boston_housing.target)

In [13]:
#Stats on dataset (eg.mean,std) for analysis
df_x.describe()

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT
count,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000
mean,3.613524,11.363636,11.136779,0.069170,0.554695,6.284634,68.574901,3.795043,9.549407,408.237154,18.455534,356.674032,12.653063
std,8.601545,23.322453,6.860353,0.253994,0.115878,0.702617,28.148861,2.105710,8.707259,168.537116,2.164946,91.294864,7.141062
min,0.006320,0.000000,0.460000,0.000000,0.385000,3.561000,2.900000,1.129600,1.000000,187.000000,12.600000,0.320000,1.730000
25%,0.082045,0.000000,5.190000,0.000000,0.449000,5.885500,45.025000,2.100175,4.000000,279.000000,17.400000,375.377500,6.950000
50%,0.256510,0.000000,9.690000,0.000000,0.538000,6.208500,77.500000,3.207450,5.000000,330.000000,19.050000,391.440000,11.360000
75%,3.677083,12.500000,18.100000,0.000000,0.624000,6.623500,94.075000,5.188425,24.000000,666.000000,20.200000,396.225000,16.955000
max,88.976200,100.000000,27.740000,1.000000,0.871000,8.780000,100.000000,12.126500,24.000000,711.000000,22.000000,396.900000,37.970000

In [21]:
#Initialize linear regression model
li_reg = linear_model.LinearRegression()

In [25]:
#Split data into 70 , 30
x_train, x_test, y_train, y_test = train_test_split(df_x,df_y,test_size=0.30, random_state = 40)

In [26]:
#Train the model with training data
li_reg.fit(x_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [27]:
#Print the coefficients of model columns
print(li_reg.coef_)

[[-1.02065294e-01  3.92035307e-02 -6.13494400e-02  3.48084703e+00
  -1.74598953e+01  3.66444175e+00 -5.31304197e-03 -1.37067900e+00
   2.51447673e-01 -9.43832755e-03 -8.58133141e-01  6.78308990e-03
  -4.96519703e-01]]

In [29]:
#print predictions on test data
y_pred = li_reg.predict(x_test)
print(y_pred)

[[21.90897572]
 [32.36829283]
 [ 9.38919345]
 [16.40673353]
 [17.80964232]
 [31.83838312]
 [25.10363218]
 [15.4942598 ]
 [21.82825591]
 [-3.63190569]
 [26.12960431]
 [15.57300292]
 [ 5.61225053]
 [ 5.58756072]
 [25.41154332]
 [34.70503462]
 [26.17912943]
 [19.13532445]
 [23.91967422]
 [14.91252997]
 [39.53465438]
 [11.07641307]
 [36.58914352]
 [26.00446715]
 [38.64469005]
 [25.17973575]
 [21.75528189]
 [18.96547913]
 [18.27571802]
 [18.60093947]
 [24.62357132]
 [23.66620392]
 [29.6987949 ]
 [24.08585329]
 [ 0.50581275]
 [24.63764742]
 [25.21913509]
 [12.19902726]
 [39.4812705 ]
 [32.23454473]
 [23.75474746]
 [ 7.056712  ]
 [20.39810217]
 [21.0026853 ]
 [31.32729178]
 [ 7.46193071]
 [12.70824342]
 [31.32832609]
 [22.40993904]
 [35.817382  ]
 [12.81513925]
 [20.71658302]
 [18.48252207]
 [ 7.65314991]
 [ 6.48378445]
 [40.45412148]
 [24.95009747]
 [24.17943728]
 [23.04271387]
 [ 7.56345617]
 [22.86100568]
 [ 9.73479018]
 [32.957889  ]
 [14.06778493]
 [28.52717573]
 [17.20171167]
 [ 3.61911076]
 [28.62629983]
 [19.42447388]
 [18.72979294]
 [19.36051351]
 [27.88976576]
 [21.11155756]
 [27.95264386]
 [34.21722447]
 [20.00321067]
 [13.39987071]
 [24.70136312]
 [16.70346939]
 [22.70991552]
 [18.90523529]
 [17.48644847]
 [18.59401509]
 [10.09315724]
 [16.78988769]
 [10.9323577 ]
 [17.072616  ]
 [20.4084587 ]
 [20.34209532]
 [19.17179969]
 [27.40674633]
 [ 7.73791552]
 [20.11982554]
 [ 5.18969717]
 [20.2172659 ]
 [ 5.18968724]
 [17.55397823]
 [27.00736521]
 [23.00701384]
 [20.51409442]
 [24.44825342]
 [16.23006422]
 [24.80902733]
 [ 5.95769186]
 [31.26003941]
 [21.69010225]
 [30.42222709]
 [31.82079134]
 [21.90982483]
 [17.40866927]
 [29.98143286]
 [39.96512278]
 [27.59995934]
 [22.03687566]
 [22.24622018]
 [14.94470564]
 [21.28339441]
 [19.3278602 ]
 [41.8844113 ]
 [21.35566086]
 [22.53418169]
 [28.98276109]
 [25.20250497]
 [16.47346987]
 [41.69742145]
 [18.17821943]
 [13.59812528]
 [24.6032745 ]
 [16.28450795]
 [28.54125121]
 [13.22639708]
 [26.69967006]
 [30.09184714]
 [23.06307131]
 [33.64391574]
 [34.87452978]
 [19.21096706]
 [20.22625076]
 [13.38442001]
 [19.58013994]
 [12.97469066]
 [35.1171442 ]
 [16.93050452]
 [25.13534002]
 [27.26167899]
 [22.67914379]
 [14.24375693]
 [23.22069174]
 [14.87303988]
 [34.55202866]
 [36.1305225 ]
 [13.89590962]]

In [34]:
print(y_test)

        0
358  22.7
197  30.3
48   14.4
450  13.4
469  20.1
369  50.0
56   24.7
139  17.8
154  17.0
414   7.0
269  20.7
26   16.6
373  13.8
386  10.5
66   19.4
161  50.0
174  22.6
395  13.1
375  15.0
378  13.1
267  50.0
444  10.8
256  44.0
82   24.8
225  50.0
252  29.6
71   21.7
132  23.0
137  17.1
9    18.9
..    ...
353  30.1
448  14.1
257  50.0
478  14.6
380  10.4
185  29.6
441  17.1
302  26.4
129  14.3
289  24.8
65   23.5
37   21.0
259  30.1
228  46.7
409  27.5
331  17.1
365  27.5
13   20.4
126  15.7
166  50.0
151  19.6
169  22.3
482  25.0
172  23.1
142  13.4
212  22.4
133  18.4
279  35.1
274  32.4
23   14.5

[152 rows x 1 columns]

In [31]:
# for model performance and accuracy usimg mse
print(np.mean((y_pred-y_test)**2))

0    31.829631
dtype: float64

In [33]:
# for model performance and accuracy usimg mse and sklearn metrics
from sklearn.metrics import mean_squared_error
print(mean_squared_error(y_test,y_pred))

31.829631155557678